### PR TITLE
Testing #23

### PR DESCRIPTION
**Pull request by OnkarRuikar**
- Testing https://github.com/yin1999/translated-content/pull/23

Here we've tested:
```bash
# Because reviewdog submits suggestion if the
# OWNER ID of the PR's HEAD and the repository are the same, or
# the branch is created from the same repository.
# As a workaround, replace those OWNER IDs with `1`.
EVENT=$(jq '.pull_request.head.repo.owner.id = 1 | .pull_request.base.repo.owner.id = 1' diff/event.json)
echo "${EVENT}" > diff/event.json
```

### CODE REVIEW

**Comment by OnkarRuikar** [comment]
@yin1999 :tada: This is a clean solution because we get to keep the original reviewdog.

Could you implement this solution in `mdn/content` repo?
- Update contents of `pr-check_markdownlint.yml` with `pr-review-lint.yml`, because we are doing only linting in the first part.
- Rename second part to `pr-lint-review-companion.yml`.

**Comment by yin1999** [comment]
> @yin1999 🎉 This is a clean solution because we get to keep the original reviewdog.
> 
> Could you implement this solution in `mdn/content` repo?
> 
> * Update contents of `pr-check_markdownlint.yml` with `pr-review-lint.yml`, because we are doing only linting in the first part.
> * Rename second part to `pr-lint-review-companion.yml`.

Of course I could. One more thing, should we recommend users to submit all suggested changes at once in [PR review](https://github.com/yin1999/translated-content/pull/24/files). I'm not sure will the reviewdog create duplicate suggestions?

**Comment by OnkarRuikar** [comment]
> I'm not sure will the reviewdog create duplicate suggestions?

It doesn't seem to. I've later pushed [a new commit containing only invalid list markers](https://github.com/yin1999/translated-content/pull/24/commits/a2d1d830f79ee2658550fade2dfbf827d7b30c63). Revewdog only posted a comment related to that.\
Also later I merged only one suggestion and the workflow didn't upload any artifact to for the second part. Could you remove the front-matter linter part from the first  workflow, it is throwing errors? Also, now instead of dumping `env` log the diff file for debugging `cat ${TMP_DIR}/diff`.

> should we recommend users to submit all suggested changes at once

We can recommend them to do it in a single batch from the `files` tab as a good practice. Because committing one by one triggers multiple workflows every time, don't know if GitHub cancels prior running workflows before starting workflows for new commits.

We can make this suggestion in PR review companion's message explaining what the auto review is doing and how to accept these changes.

**Comment by yin1999** [comment]
Thanks for the try and suggestions @OnkarRuikar :+1:

**Comment by OnkarRuikar** [comment]
@yin1999 could you hold off on the PR in `mdn/content` repo? Another approach has been suggested by Leo let me try that first.

**Comment by yin1999** [comment]
> @yin1999 could you hold off on the PR in `mdn/content` repo? Another approach has been suggested by Leo let me try that first.

Yes, please go ahead!

**Comment by yin1999** [comment]
Closing as the new approach (mdn/content#28363) works great.

**Pull request closed without merging**
