### PR TITLE
Test reviewdog companion workflow style setup

### PR DESCRIPTION
**Pull request by OnkarRuikar**
Trying to see if any of the involved workflow gets write access.

### CODE REVIEW

**Comment by OnkarRuikar** [comment]
Why do we have to checkout the PR again? Can reviewdog work simply based on the diff file and the event path environment variable?
Looks like they are using `GITHUB_EVENT_PATH` [to get all the info](https://github.com/reviewdog/reviewdog/blob/0982b5e7d99640cb55f1a849390b24f9d48cfcbe/cienv/github_actions.go#L77-L86):
```
func getBuildInfoFromGitHubActionEventPath(eventPath string) (*BuildInfo, bool, error) {
	event, err := loadGitHubEventFromPath(eventPath)
	if err != nil {
		return nil, false, err
	}
	info := &BuildInfo{
		Owner:       event.Repository.Owner.Login,
		Repo:        event.Repository.Name,
		PullRequest: event.PullRequest.Number,
		Branch:      event.PullRequest.Head.Ref,
		SHA:         event.PullRequest.Head.Sha,
	}
```

**Comment by yin1999** [comment]
I've update the workflow to use head sha instead od ref, could you merge main branch or push another commit to retrigger the workflow :)

**Comment by yin1999** [comment]
> Why do we have to checkout the PR again? Can reviewdog work simply based on the diff file and the event path environment variable? Looks like they are using `GITHUB_EVENT_PATH` [to get all the info](https://github.com/reviewdog/reviewdog/blob/0982b5e7d99640cb55f1a849390b24f9d48cfcbe/cienv/github_actions.go#L77-L86):
> 
> ```
> func getBuildInfoFromGitHubActionEventPath(eventPath string) (*BuildInfo, bool, error) {
> 	event, err := loadGitHubEventFromPath(eventPath)
> 	if err != nil {
> 		return nil, false, err
> 	}
> 	info := &BuildInfo{
> 		Owner:       event.Repository.Owner.Login,
> 		Repo:        event.Repository.Name,
> 		PullRequest: event.PullRequest.Number,
> 		Branch:      event.PullRequest.Head.Ref,
> 		SHA:         event.PullRequest.Head.Sha,
> 	}
> ```

Yes, but I've tried this before (do not checkout the pull request), and the workflow just failed, see: https://github.com/yin1999/translated-content/actions/runs/5733455154/job/15538168451

image

**Comment by yin1999** [comment]
It seems that the GitHub token don't have the write permission yet. But I think we could use the mdn-bot token instead! As the pr-review-companion just used some secret token: https://github.com/mdn/translated-content/blob/bbd1e5d1f4fb9055d181891d66c6fc596a5332d9/.github/workflows/pr-review-companion.yml#L116-L117.

I'd like to setup a PAT and try again :)

**Comment by OnkarRuikar** [comment]
https://github.com/yin1999/translated-content/actions/runs/5735118338/job/15542340194#step:6:14
> reviewdog: This GitHub token doesn't have write permission of Review API [1], 

It's the same issue we are facing in the `mdn/content` repo. It is not letting guest triggered workflows have write permissions. I don't think adding `permissions: write-all` to the companion workflow file will work but we can try. How does the normal review companion is able to add comment on PR yari uses the same 	GITHUB_TOKEN in its scripts...

**Comment by yin1999** [comment]
Hi @OnkarRuikar, I've read the document [here](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/). If I understand correctly, the second workflow should have the write permission.

Edit: yes, the [log](https://github.com/yin1999/translated-content/actions/runs/5735118338/job/15542340194#step:1:16) just show that. I think I need to spend more time on how the reviewdog creates PR review comment.

**Comment by OnkarRuikar** [comment]
> Hi @OnkarRuikar, I've read the document [here](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/). If I understand correctly, the second workflow should have the write permission.

It has the write permissions see the [lint companion workfow logs](https://github.com/yin1999/translated-content/actions/runs/5735118338/job/15542340194#step:1:26). Is there a possibility that reviewdog has a bug?

**Comment by yin1999** [comment]
> > Hi @OnkarRuikar, I've read the document [here](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/). If I understand correctly, the second workflow should have the write permission.
> 
> It has the write permissions see the [lint companion workfow logs](https://github.com/yin1999/translated-content/actions/runs/5735118338/job/15542340194#step:1:26). Is there a possibility that reviewdog has a bug?

I found that, https://github.com/reviewdog/reviewdog/blob/0982b5e7d99640cb55f1a849390b24f9d48cfcbe/cienv/github_actions.go#L118

reviewdog uses `isForkedRepo` (compare the ownerID of repo's owner and PR) to check if the token has write permission. So this workflow failed.

**Comment by OnkarRuikar** [comment]
> reviewdog uses `isForkedRepo` and compare the ownerID of repo's owner and PR to check if the token has write permission. So this workflow failed.

LOL. I was going to  mention the same function! So they are speculating that the token is read only themselves, without even sending the requests to GitHub APIs. :man_facepalming: 
Our token has write access but they are mistakenly deciding that it is read only. We could file a bug there cos this is a valid implementation and needs to work.

**Comment by yin1999** [comment]
> LOL. I was going to mention the same function! So they are speculating that the token is read only themselves, without even sending the requests to GitHub APIs. man_facepalming Our token has write access but they are mistakenly deciding that it is read only. We could file a bug there cos this is a valid implementation and needs to work.

There is a [discuession](https://github.com/orgs/community/discussions/25259#discussioncomment-5999008), but no one has came up with how to check the permission of `secret.GITHUB_TOKEN`.

**Comment by OnkarRuikar** [comment]
> > LOL. I was going to mention the same function! So they are speculating that the token is read only themselves, without even sending the requests to GitHub APIs. man_facepalming Our token has write access but they are mistakenly deciding that it is read only. We could file a bug there cos this is a valid implementation and needs to work.
> 
> There is a [discuession](https://github.com/orgs/community/discussions/25259#discussioncomment-5999008), but no one has came up with how to check the permission of `secret.GITHUB_TOKEN`.

But they can simply make the GitHub API request and upon receiving HTTP 403 response go to fallback options...

**Comment by yin1999** [comment]
Yes, maybe they could do that (or could add an option to explicitly declare the token has the write permission). Would you like to create an issue there :)

**Comment by yin1999** [comment]
Hey @OnkarRuikar! There is someone created a PR to fix that: reviewdog/reviewdog#1406

**Comment by yin1999** [comment]
As a workaround, we could remove the `PullRequest.Head.Repo.Owner.ID` and `PullRequest.Base.Repo.Owner.ID` fields from the event file (I've checked the reference of them, they are only used to check if the branch is from forked repo). The fixing PR in reviewdog has been idle for 4 months.

image

**Comment by OnkarRuikar** [comment]
> As a workaround, we could remove the `PullRequest.Head.Repo.Owner.ID` and `PullRequest.Base.Repo.Owner.ID` fields from the event file (I've checked the reference of them, they are only used to check if the branch is from forked repo). The fixing PR in reviewdog has been idle for 4 months.

Removing them completely may throw property undefined error. We need to assign them the same values before running reviewdog binary. But depending on which value(head owner or base owner) we update, reviewdog may face some side effects while calling GitHub APIs.

I am [trying other approach ](https://github.com/yin1999/translated-content/pull/21), could you let the workflow run.

**Comment by yin1999** [comment]
> We need to assign them the same values. Removing them completely may throw property undefined error.

Actually, default unmarshal method in GOLANG would set those fields with `0`. But to avoid reviewdog modifying the check for the field in the future (although unlikely to happen), I replaced the ID with `1`.

@OnkarRuikar. Could you try to push another commit :)

**Comment by yin1999** [comment]
Closing as the new approach (mdn/content#28363) works great.

**Pull request closed without merging**
